dist: trusty
language: rust

rust:
- stable
- nightly

matrix:
  allow_failures:
  - rust: nightly

install:
- rustup component add clippy rustfmt

script:
- cargo build --all-features
- cargo test --all-features
- cargo clippy --all-features -- -Dwarnings
- cargo fmt --all --all-features -- --check
